### ISSUE TITLE
Breaks with server-side rendering

### ISSUE THREAD

**Issue by benoneal** [filestack/filestack-js#11]
We have a react application with server-side rendering. Filestack-js attempts to extend the browser-only `File` prototype at compile-time. 

Please only do this in the `init()` method, so that we can use this lib in our application.

**Comment by msaglietto** [comment]
We have the same problem ... here is the error 
```
Using browser-only version of superagent in non-browser environment

/Users/msaglietto/Projects/test/node_modules/filestack-js/dist/filestack.js:3
        typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
                                                                                 ^
ReferenceError: File is not defined
    at /Users/msaglietto/Projects/test/node_modules/filestack-js/node_modules/api-client/api-client.es2015.js:4:25975
    at commonjsGlobal (/Users/msaglietto/Projects/test/node_modules/filestack-js/dist/filestack.js:3:82)
    at Object.<anonymous> (/Users/msaglietto/Projects/test/node_modules/filestack-js/dist/filestack.js:6:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/msaglietto/Projects/test/build/webpack:/external "filestack-js":58:1)
    at __webpack_require__ (/Users/msaglietto/Projects/test/build/webpack:/webpack/bootstrap 4ac84d040412742c7454:19:1)
    at Object.module.exports.Object.defineProperty.value (/Users/msaglietto/Projects/test/build/webpack:/src/components/common/forms/upload/FileStack.js:44:1)
    at __webpack_require__ (/Users/msaglietto/Projects/test/build/webpack:/webpack/bootstrap 4ac84d040412742c7454:19:1)
```

**Comment by velveteer** [comment]
Thanks for the feedback! I will look into getting this resolved soon.

**Comment by velveteer** [comment]
@benoneal @msaglietto 0.6.0 has a rewritten upload method and should not be referencing the File prototype at compile time. Let us know if this resolves the problem for you.

**Comment by msaglietto** [comment]
Sorry im on vacations ... I had a chance to do a quick test like: 

```
import filestack from 'filestack-js';
const apiKey = '';
export const client = filestack.init(apiKey);
```

I get the module printed on the  server console
```
node_modules/filestack-js/dist/filestack.js:2
(function(global,factory){typeof exports==="object"&&typeof module!=="undefined"?module.exports=factory():typeof
```

I will check further when I can sit with my computer

**Comment by zimme** [comment]
@velveteer, I'm trying to use this on the server in Meteor and previous to `0.6.0` of this package I got the same error as @msaglietto and with version `0.6.0` I'm getting the following error.
```
Using browser-only version of superagent in non-browser environment
/Users/zimme/.meteor/packages/meteor-tool/.1.4.4_2.1sgods7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Cannot read property 'loader' of undefined
    at /Users/zimme/Development/candid/ats/node_modules/filestack-js/dist/filestack.js:9:25495
    at commonjsGlobal (/Users/zimme/Development/candid/ats/node_modules/filestack-js/dist/filestack.js:2:97)
    at Object.<anonymous> (/Users/zimme/Development/candid/ats/node_modules/filestack-js/dist/filestack.js:2:190)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at npmRequire (/Users/zimme/Development/candid/ats/.meteor/local/build/programs/server/npm-require.js:133:10)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

I've tracked it down to the file `picker.js` in your picker package.

I believe it's the following code that's the culprit.
```
...
// -----------------------------------------------------------------------------
// Init

var initializeGlobalNamespace$1 = function initializeGlobalNamespace() {
  var namespace = void 0;
  if ((typeof window === 'undefined' ? 'undefined' : _typeof(window)) === 'object') {
    namespace = window.filestackInternals;
    if (!namespace) {
      namespace = {};
      window.filestackInternals = namespace;
    }
    if (!namespace.loader) {
      namespace.loader = {
        modules: {}
      };
    }
  }
  return namespace;
};

var filestackInternals = initializeGlobalNamespace$1();

// -----------------------------------------------------------------------------
// Modules loading

// All modules share global "register", so different instances of loader can
// communicate which modules were already loaded and which not.
var modules$1 = filestackInternals.loader.modules;
....
```
I believe this check `(typeof window === 'undefined' ? 'undefined' : _typeof(window)) === 'object'` isn't true on the server and because of that `namespace` won't be initialized which makes the following code fail.
```
var modules$1 = filestackInternals.loader.modules;
```

**Comment by zimme** [comment]
I know you probably have your reasons for not having all parts of the library open-sourced, but please consider it as I'd be happy and I believe others would be too, to contribute where we feel we are able.

**Comment by zimme** [comment]
Any thoughts on this?

**Comment by velveteer** [comment]
@zimme Yeah looks like I missed one more spot where we assume a browser environment. I will hopefully have this fixed in 0.7.0.

**Comment by sudowned** [comment]
Can we get an update on this? This is causing us serious problems as well.

**Comment by velveteer** [comment]
@sudowned I have it resolved, we're just prepping for the 0.7.0 release. It's a larger release than usual so we're testing for a bit, but hopefully we'll have something out next week. Either way I will update this issue when it's out.

**Comment by velveteer** [comment]
To those subscribed on this one, 0.7.0 is out as of yesterday. I would be very grateful if anyone can report back to confirm if 0.7.0 resolved this or not. :)

**Comment by msaglietto** [comment]
Is not breaking anymore for me .. thanks you very much
